<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Solicitudes de contacto - OptiGest</title><link rel="stylesheet" href="${ctx}/Css/bootstrap.min.css"><link rel="stylesheet" href="${ctx}/Css/GestionContacto.css"><link rel="stylesheet" href="${ctx}/Css/ResponsiveBase.css?v=4"></head>
<body class="gestion-contacto-page"><main class="container py-5 gc-wrap"><header class="gc-header"><div><h1 class="h2 gc-title">Solicitudes de contacto</h1><p class="gc-copy">Revisa y atiende las solicitudes recibidas desde la página de contacto.</p></div><a class="btn gc-back" href="${ctx}/Configuracion">Volver a configuración</a></header>
<c:if test="${param.atendido == '1'}"><div class="alert alert-success">Solicitud marcada como atendida.</div></c:if><c:if test="${param.personalRegistrado == '1'}"><div class="alert alert-success">Personal registrado correctamente. La solicitud fue marcada como atendida.</div></c:if><c:if test="${param.claveRenovada == '1'}"><div class="alert alert-success">Nueva contraseña temporal generada. La anterior dejó de funcionar.</div></c:if><c:if test="${param.error == '1'}"><div class="alert alert-danger">No se pudo actualizar la solicitud.</div></c:if>
<section class="gc-list"><c:forEach var="m" items="${mensajes}"><article class="gc-request"><div class="gc-date"><strong>Recibida</strong><br>${m.fecha}</div><div class="gc-person"><strong>${m.nombre} ${m.apellidos}</strong><small>${empty m.tipoDocumento ? 'Documento' : m.tipoDocumento}: ${m.documento}</small><a href="mailto:${m.email}">${m.email}</a><small>${m.telefono}</small><small>Dirección: ${m.direccion}</small></div><div class="gc-details"><span class="gc-type">${m.tipoSolicitud}</span><c:if test="${not empty m.usuarioDeseado}"><div class="gc-user"><strong>Usuario deseado:</strong> ${m.usuarioDeseado}</div></c:if></div><div class="gc-message"><strong>${m.asunto}</strong><p>${m.mensaje}</p></div><div class="gc-actions"><c:choose><c:when test="${m.atendido}"><span class="gc-status gc-done">Atendida</span><c:if test="${not empty claveGenerada && m.personalId == claveGeneradaPersonalId}"><section class="gc-password-inline"><strong>Clave temporal</strong><code id="claveGenerada">${claveGenerada}</code><time data-expira="${claveGeneradaExpiraEn}">Calculando…</time><button type="button" data-copiar-clave>Copiar</button></section></c:if><c:if test="${not empty m.personalId}"><c:choose><c:when test="${m.personalDebeCambiarClave}"><form method="post" action="${ctx}/RegenerarClaveTemporal"><input type="hidden" name="personalId" value="${m.personalId}"><button class="gc-action-btn gc-renovar-btn" type="submit">Generar otra clave</button></form></c:when><c:otherwise><button class="gc-action-btn gc-renovar-btn gc-renovar-btn-disabled" type="button" disabled title="El empleado ya actualizó su contraseña.">Clave actualizada</button></c:otherwise></c:choose></c:if></c:when><c:otherwise><span class="gc-status gc-pending">Pendiente</span><c:if test="${m.tipoSolicitud == 'CREAR CUENTA' || m.tipoSolicitud == 'Crear cuenta'}"><a class="btn btn-sm gc-action-btn" href="${ctx}/GuardarPersonal?solicitudId=${m.id}">Registrar personal</a></c:if><form method="post" action="${ctx}/GestionContacto"><input type="hidden" name="id" value="${m.id}"><button class="btn btn-sm gc-action-btn" type="submit">Marcar atendida</button></form></c:otherwise></c:choose></div></article></c:forEach><c:if test="${empty mensajes}"><div class="gc-empty">No hay solicitudes activas.</div></c:if></section>
<details class="gc-history"><summary>Historial de solicitudes atendidas <span>(${mensajesArchivados.size()})</span></summary><div class="gc-history-list"><c:choose><c:when test="${empty mensajesArchivados}"><p>No hay solicitudes archivadas todavía.</p></c:when><c:otherwise><c:forEach var="m" items="${mensajesArchivados}"><article><strong>${m.nombre} ${m.apellidos}</strong><span>${m.tipoSolicitud}</span><small>Atendida: ${m.fechaAtencion}</small><p>${m.asunto}</p></article></c:forEach></c:otherwise></c:choose></div></details>
</main><script>document.addEventListener('click',function(e){if(e.target.matches('[data-copiar-clave]'))navigator.clipboard.writeText(document.getElementById('claveGenerada').textContent).then(function(){e.target.textContent='Copiada';});});document.querySelectorAll('[data-expira]').forEach(function(el){var fecha=new Date(el.dataset.expira);function actualizar(){var ms=fecha-new Date();if(ms<=0){el.textContent='Vencida';return;}var m=Math.floor(ms/60000),s=Math.floor(ms/1000)%60;el.textContent=m+' min '+String(s).padStart(2,'0')+' s';}actualizar();setInterval(actualizar,1000);});</script></body></html>
